name: Contracts Deploy
on:
  push:
    paths:
      - 'packages/contracts/**'
    branches:
      - 'develop'
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Compile
        run: cd packages/contracts && yarn run compile
      - name: Run Hardhat Tests
        env:
          REPORT_GAS: true
        run: cd packages/contracts && yarn run test
  prepare:
    needs: [test]
    runs-on: ubuntu-latest
    outputs:
      environment: ${{ steps.prepare.outputs.environment }}
      tags: ${{ steps.prepare.outputs.tags }}
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        id: prepare
        run: node .github/helpers/contracts/prepare.js '${{ github.ref }}'
  build-deploy:
    runs-on: ubuntu-latest
    needs: [prepare]
    environment: ${{ needs.prepare.outputs.environment }}
    strategy:
      fail-fast: true
      matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: yarn install --pure-lockfile
      - name: Compile
        run: cd packages/contracts && yarn run compile
      - name: Deploy
        run: cd packages/contracts && yarn run deploy --network $NETWORK --tags "DAOFactory,TokenFactory,${{ needs.prepare.outputs.tags }}"
        env:
          ETH_KEY: ${{ secrets.ETH_KEY }}
          NETWORK: ${{ matrix.network }}
          ETHERSCAN_KEY: ${{ secrets.ETHERSCAN_KEY }}
          ARBISCAN_KEY: ${{ secrets.ARBISCAN_KEY }}
          POLYGONSCAN_KEY: ${{ secrets.POLYGONSCAN_KEY }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.network}}
          path: ./packages/contracts/deployments/*
          retention-days: 1
  conclude:
    runs-on: ubuntu-latest
    needs: ['build-deploy']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artefacts
      - name: Update Releases.md
        run: node .github/helpers/contracts/updateReleasesMD.js
      - name: Update active_contracts.json
        run: node .github/helpers/contracts/updateActiveContractsJSON.js
      - name: Commit changes
        run: |
          git fetch
          git pull
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add active_contracts.json
          git add packages/contracts/Releases.md
          git commit -am "Updates files with deployed contract addresses"
          git push
  subgraphUpdate:
    runs-on: ubuntu-latest
    needs: ['build-deploy']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: artefacts
      - name: Update Subgraph manifests
        run: node .github/helpers/subgraph/updateManifest.js
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          add-paths: ./packages/subgraph/	
          commit-message: Update subgraph manifests
          branch: feature/update-manifests
          delete-branch: true
          branch-suffix: short-commit-hash
          title: Updates Subgraph manifests
          reviewers: Rekard0,RakeshUP